feat: 경주로건설
Boostcamp-AI-Tech-1-15/algorithm_study pull request #4
Opened 2021-08-09 07:07 UTC by l-yohai

# 문제

경주로건설

## 해결방법 및 핵심로직

DP + BFS로 해결하였습니다.

너비우선으로 탐색하면서 DP Table에 최소 비용들을 저장하는 bfs함수를 만들고

오른쪽으로 먼저 출발했을때와 아래로 먼저 출발했을 때의 최소값을 반환하도록 작성했습니다.

## 작성한 테스트케이스 (있을 경우만)

2021-08-11 07:33 UTC, 20180707jun approved these changes

2021-08-11 19:29 UTC, 20180707jun approved these changes

2021-08-11 19:29 UTC, 20180707jun approved these changes
코드가독성이 정말 좋은 것 같습니다.!!

2021-08-12 10:07 UTC, ddobokki approved these changes

2021-08-12 10:07 UTC, ddobokki commented on week_1/경주로건설/yohan.py
> +            for i in range(4):
하드코딩 방지용 매크로 변수들을 선언한김에 
위쪽 변수 선언 부분에
DIRECTIONS = [UP, DOWN, LEFT, RIGHT] 
( 이부분의 변수 이름은 잘 모르겠습니다. direction의 복수형이 찾아보니 direction이네요... dirs 정도는 어떨까요? 또는 리스트)
for d in DIRECTIONS:
....

이런식으로 for문을 구성하는건 어떨까요?

2021-08-12 10:07 UTC, ddobokki commented on week_1/경주로건설/yohan.py
> +
대단히 읽기 쉬운코드 같습니다.
많이 배워갑니다!

2021-08-12 10:19 UTC, EP000 approved these changes
코드가 깔끔하네요 많이 배워갑니다~

2021-08-12 10:21 UTC, l-yohai commented on week_1/경주로건설/yohan.py
> +            for i in range(4):
엇.. 제 미천한 영어실력이 들통났군요. 좋은지적 감사합니다! 제가 놓친 부분이 있었네요, 말씀하신 대로 변경했습니다! 훨씬 좋은 것 같네요 ㅎㅎ 감사합니다!

2021-08-12 11:24 UTC, keemdy commented on README.md
>  - 칭찬에 익숙해집시다.
코드 정말 잘 짜셨네요 !

2021-08-12 11:40 UTC, keemdy approved these changes
요한님처럼 변수 설정해 놓는 것 이해하기 쉬워서 좋네요 !

2021-08-12 12:30 UTC, minji-o-j requested changes

2021-08-12 12:30 UTC, minji-o-j commented on week_1/경주로건설/yohan.py
> +            for direction in DIRS:
28번째 줄 변수 이름을 변경하면서  27번째 줄과 이름이 같아져, 아래 과정에서 값이 달라지게 될 것 같습니다!

2021-08-12 12:33 UTC, minji-o-j requested changes

2021-08-12 12:33 UTC, minji-o-j commented on week_1/경주로건설/yohan.py
> +            for direction in DIRS:
28번째 줄 변수 이름을 변경하면서 27번째 줄과 이름이 같아져, 아래 과정에서 값이 달라지게 될 것 같습니다!

2021-08-12 12:58 UTC, l-yohai commented on week_1/경주로건설/yohan.py
> +            for direction in DIRS:
헉 테스트를 해보지 않고 올렸더니 오류가 생긴지도 몰랐네요.. 반성하겠습니다. 수정했어요! @minji-o-j

2021-08-12 13:00 UTC, minji-o-j approved these changes
수고하셨습니다!

2021-08-12 15:55 UTC, ddeokbboki-good approved these changes
알아보기 쉽다는 것이 가장 큰 장점인 것 같습니다. 수고하셨습니다~

2021-08-12 15:55 UTC, merged